[package]
name = "flashwright-bootimg-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.flashwright-bootimg]
path = ".."

[[bin]]
name = "ramdisk"
path = "fuzz_targets/ramdisk.rs"
test = false
doc = false
bench = false

[[bin]]
name = "header"
path = "fuzz_targets/header.rs"
test = false
doc = false
bench = false

[[bin]]
name = "cpio"
path = "fuzz_targets/cpio.rs"
test = false
doc = false
bench = false

[workspace]
